/*
 * Copyright (c) 2014, Francis Galiegue (fgaliegue@gmail.com)
 *
 * This software is dual-licensed under:
 *
 * - the Lesser General Public License (LGPL) version 3.0 or, at your option, any
 *   later version;
 * - the Apache Software License (ASL) version 2.0.
 *
 * The text of both licenses is available under the src/resources/ directory of
 * this project (under the names LGPL-3.0.txt and ASL-2.0.txt respectively).
 *
 * Direct link to the sources:
 *
 * - LGPL 3.0: https://www.gnu.org/licenses/lgpl-3.0.txt
 * - ASL 2.0: http://www.apache.org/licenses/LICENSE-2.0.txt
 */

/**
 * Subsequences of a {@link com.github.fge.largetext.LargeText}
 *
 * <p>This package deals with calls to {@link
 * com.github.fge.largetext.LargeText#charAt(int)} and {@link
 * com.github.fge.largetext.LargeText#subSequence(int, int)}. The goal is to
 * create a sequence with the minimal set of {@link
 * com.github.fge.largetext.load.TextRange}s enclosing the required index or
 * indices.</p>
 *
 * <p>This can either be a single range {@link
 * com.github.fge.largetext.sequence.SingleTextRangeCharSequence} or more than
 * one range ({@link
 * com.github.fge.largetext.sequence.MultiTextRangeCharSequence}), or even the
 * empty sequence {@link com.github.fge.largetext.sequence.EmptyCharSequence}).
 * </p>
 *
 * <p>The {@link com.github.fge.largetext.sequence.CharSequenceFactory} class
 * is in charge of generating such ranges; in turn, it is used by sequences
 * generated by this package to, again, obtain subsequences.</p>
 */
package com.github.fge.largetext.sequence;